"""Orchestrate FAST-Calib runs without touching its source.

Each camera-LiDAR pair defined in sensors.yaml is calibrated independently.
After all pairs are calibrated, inter-camera transforms are derived
automatically for any two cameras that share the same LiDAR.

Path responsibilities
---------------------
state_path  ($XDG_STATE_HOME/ros/fast_calib)
    Transient working data:
    - scenes/<scene>/<camera>/lidar_bag/    recorded rosbag2 directories
    - scenes/<scene>/<camera>/image.png     snapshot images
    - configs/<scene>_<camera>_params.yaml  generated by ConfigManager.build()
    - <camera>/circle_center_record.txt     accumulated by fast_calib

output_path  (user-specified, default ./fast_calib_output)
    Final user-facing results:
    - <camera>/calib_result.txt
    - <camera>/multi_calib_result.txt
    - <camera>/colored_cloud.pcd
    - <camera>/qr_detect.png
    - inter_camera/T_<camB>_<camA>.txt      derived inter-camera transforms
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import yaml

from .config_manager import ConfigManager, _MULTI_NODE
from .sensor_config import CameraConfig, SensorConfig


@dataclass
class PairScene:
    """One collected scene for a specific camera-LiDAR pair."""

    scene_name: str
    camera_name: str
    bag: str
    image: str
    intrinsics: Dict[str, Any]


@dataclass
class WorkflowManager:
    """Track scenes per camera-LiDAR pair and dispatch calibration runs."""

    sensor_config: SensorConfig
    state_path: Path
    output_path: Path
    scenes: List[PairScene] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.state_path = Path(self.state_path)
        self.output_path = Path(self.output_path)
        self.state_path.mkdir(parents=True, exist_ok=True)
        self.output_path.mkdir(parents=True, exist_ok=True)

    # --- scene management -------------------------------------------------

    def add_scene(self, scene: PairScene) -> None:
        self.scenes.append(scene)

    def scenes_for(self, camera_name: str) -> List[PairScene]:
        return [s for s in self.scenes if s.camera_name == camera_name]

    # --- config generation ------------------------------------------------

    def _build_config(self, scene: PairScene) -> Path:
        """Generate a qr_params.yaml for one scene into the state directory."""
        camera = next(
            c for c in self.sensor_config.cameras if c.name == scene.camera_name
        )
        lidar = self.sensor_config.lidar_for(camera)
        cam_output = self.output_path / scene.camera_name
        cam_output.mkdir(parents=True, exist_ok=True)

        configs_dir = self.state_path / 'configs'
        save_path = configs_dir / f'{scene.scene_name}_{scene.camera_name}_params.yaml'

        cfg = ConfigManager.build(
            intrinsics=scene.intrinsics,
            target=self.sensor_config.target.as_dict(),
            bag_path=scene.bag,
            image_path=scene.image,
            output_path=str(cam_output),
            lidar_topic=lidar.topic,
            save_path=save_path,
            filter_bounds=self.sensor_config.filter.as_dict(),
        )
        return cfg.config_path

    # --- calibration runs -------------------------------------------------

    @staticmethod
    def _run(cmd: List[str]) -> int:
        """Run a subprocess, streaming output, returning its exit code."""
        print(f'\n$ {" ".join(cmd)}\n')
        return subprocess.run(cmd, check=False).returncode

    def run_single_scene(self, scene: PairScene) -> bool:
        """Run single-scene calibration for one camera-LiDAR pair."""
        cfg_path = self._build_config(scene)
        rc = self._run([
            'ros2', 'run', 'fast_calib', 'fast_calib',
            '--ros-args', '--params-file', str(cfg_path),
        ])
        return rc == 0

    def run_multi_scene(self, camera: CameraConfig) -> bool:
        """Run multi-scene calibration for one camera using accumulated records.

        Requires at least 3 scenes for the given camera.
        """
        cam_scenes = self.scenes_for(camera.name)
        if len(cam_scenes) < 3:
            print(
                f"Camera '{camera.name}' needs at least 3 scenes "
                f"(have {len(cam_scenes)})."
            )
            return False

        # Build a minimal config pointing at the camera's output directory
        # (where circle_center_record.txt has been accumulating).
        cam_output = self.output_path / camera.name
        lidar = self.sensor_config.lidar_for(camera)
        save_path = self.state_path / 'configs' / f'multi_{camera.name}_params.yaml'

        # Reuse the last scene's intrinsics — multi_fast_calib only needs
        # output_path and lidar_topic from the param file.
        last = cam_scenes[-1]
        ConfigManager.build(
            intrinsics=last.intrinsics,
            target=self.sensor_config.target.as_dict(),
            bag_path=last.bag,
            image_path=last.image,
            output_path=str(cam_output),
            lidar_topic=lidar.topic,
            save_path=save_path,
            filter_bounds=self.sensor_config.filter.as_dict(),
            node_name=_MULTI_NODE,
        )

        rc = self._run([
            'ros2', 'run', 'fast_calib', 'multi_fast_calib',
            '--ros-args', '--params-file', str(save_path),
        ])
        return rc == 0

    # --- inter-camera transforms ------------------------------------------

    def compute_inter_camera_transforms(self) -> Dict[str, np.ndarray]:
        """Derive T_camB_camA for all camera pairs sharing a LiDAR.

        Reads the best available result file for each camera, then computes:
            T_B_A = T_B_lidar @ inv(T_A_lidar)

        Returns a dict keyed by 'T_<camB>_<camA>' with 4x4 numpy arrays.
        Saves each transform as a text file under output_path/inter_camera/.
        """
        # Load result matrices for each camera that has one.
        matrices: Dict[str, np.ndarray] = {}
        for camera in self.sensor_config.cameras:
            T = self._load_result_matrix(camera.name)
            if T is not None:
                matrices[camera.name] = T

        inter_dir = self.output_path / 'inter_camera'
        inter_dir.mkdir(parents=True, exist_ok=True)
        results: Dict[str, np.ndarray] = {}

        cameras = self.sensor_config.cameras
        for i, cam_a in enumerate(cameras):
            for cam_b in cameras[i + 1:]:
                # Only derive if they share the same LiDAR.
                if cam_a.lidar != cam_b.lidar:
                    continue
                if cam_a.name not in matrices or cam_b.name not in matrices:
                    print(
                        f"Skipping T_{cam_b.name}_{cam_a.name}: "
                        f"missing result for one or both cameras."
                    )
                    continue

                T_a = matrices[cam_a.name]
                T_b = matrices[cam_b.name]
                T_b_a = T_b @ np.linalg.inv(T_a)

                key = f'T_{cam_b.name}_{cam_a.name}'
                results[key] = T_b_a
                self._save_inter_camera(inter_dir, key, T_b_a, cam_a.name, cam_b.name)

        return results

    def _load_result_matrix(self, camera_name: str) -> Optional[np.ndarray]:
        """Parse the 4x4 transformation matrix from a fast_calib result file."""
        cam_output = self.output_path / camera_name
        for candidate in ('multi_calib_result.txt', 'calib_result.txt'):
            path = cam_output / candidate
            if not path.is_file():
                continue
            try:
                return _parse_result_matrix(path)
            except Exception as exc:  # noqa: BLE001
                print(f"Warning: could not parse {path}: {exc}")
        return None

    @staticmethod
    def _save_inter_camera(
        inter_dir: Path,
        key: str,
        T: np.ndarray,
        cam_a: str,
        cam_b: str,
    ) -> None:
        out = inter_dir / f'{key}.txt'
        with out.open('w') as fh:
            fh.write(f'# T_{cam_b}_{cam_a}: transforms points from {cam_a} to {cam_b}\n')
            fh.write(f'# T_{cam_b}_{cam_a} = T_{cam_b}_lidar @ inv(T_{cam_a}_lidar)\n')
            fh.write('T: [\n')
            for row in T:
                fh.write(
                    f'  {row[0]:.8f}, {row[1]:.8f}, {row[2]:.8f}, {row[3]:.8f},\n'
                )
            fh.write(']\n')
        print(f'[Inter-camera] Saved {key} → {out}')

    # --- result display ---------------------------------------------------

    def latest_result(self, camera_name: str) -> Optional[str]:
        """Return the most recent result text for a camera, if present."""
        cam_output = self.output_path / camera_name
        for candidate in ('multi_calib_result.txt', 'calib_result.txt'):
            path = cam_output / candidate
            if path.is_file():
                return path.read_text()
        return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_result_matrix(path: Path) -> np.ndarray:
    """Parse Rcl and Pcl from a fast_calib result file into a 4x4 matrix.

    Expected format (FAST-LIVO2):
        Rcl: [ r00, r01, r02,
               r10, r11, r12,
               r20, r21, r22]
        Pcl: [ tx, ty, tz]
    """
    text = path.read_text()
    raw = yaml.safe_load(text)

    rcl = raw.get('Rcl') or raw.get('rcl')
    pcl = raw.get('Pcl') or raw.get('pcl')

    if rcl is None or pcl is None:
        raise ValueError(f'Could not find Rcl/Pcl in {path}')

    R = np.array(rcl, dtype=float).reshape(3, 3)
    t = np.array(pcl, dtype=float).reshape(3, 1)

    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = t[:, 0]
    return T
